# This file was generated by GoReleaser. DO NOT EDIT.
cask "octoscope" do
  on_macos do
    depends_on formula: "terminal-notifier"
  end

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:  ["-dr", "com.apple.quarantine", "octoscope"],
          chdir: "."
    end
  end

  version "0.36.1"

  on_macos do
    on_arm do
      sha256 "922ff56e9cb6a18581b22e74afc443bbb83a04c44f54583564b01aab64677e97"
      url "https://github.com/gfazioli/octoscope/releases/download/v#{version}/octoscope_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "316f6363f1257998fe0ebdf9f791d38164446b1b797cb231365b28c1ca2609d4"
      url "https://github.com/gfazioli/octoscope/releases/download/v#{version}/octoscope_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "697333be8df0b90e110bc36e5aafdd09eec0a672cd1e80c54cfaa663d91aed28"
      url "https://github.com/gfazioli/octoscope/releases/download/v#{version}/octoscope_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6b68ab0f14996e7ee95119697c46dd61ba98b35ff070a0840c531a745c407a37"
      url "https://github.com/gfazioli/octoscope/releases/download/v#{version}/octoscope_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "octoscope"
  desc "Terminal dashboard for your GitHub account"
  homepage "https://github.com/gfazioli/octoscope"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "octoscope"

  # No zap stanza required
end
