# This file was generated by GoReleaser. DO NOT EDIT.
cask "octoscope" do
  on_macos do
    depends_on formula: "terminal-notifier"
  end

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:  ["-dr", "com.apple.quarantine", "octoscope"],
          chdir: "."
    end
  end

  version "0.37.0"

  on_macos do
    on_arm do
      sha256 "c7e7457ee2700d12d36ba5ab8a64aee4e6e2e2d41f8d33fc305571a47cdba894"
      url "https://github.com/gfazioli/octoscope/releases/download/v#{version}/octoscope_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "b8550ca0920b6abf81602c88bcfb02e8428f033871d5546e944858d877bfccfa"
      url "https://github.com/gfazioli/octoscope/releases/download/v#{version}/octoscope_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2d1fd8556a5ec29ccad4844612388e906803a9c31943877ff7ad05c6ddc83783"
      url "https://github.com/gfazioli/octoscope/releases/download/v#{version}/octoscope_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9b01721cd5d18c6f37021319b17fe79e1a1603bfb2af9048f1f962fb09419c1c"
      url "https://github.com/gfazioli/octoscope/releases/download/v#{version}/octoscope_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "octoscope"
  desc "Terminal dashboard for your GitHub account"
  homepage "https://github.com/gfazioli/octoscope"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "octoscope"

  # No zap stanza required
end
