# This file was generated by GoReleaser. DO NOT EDIT.
cask "octoscope" do
  on_macos do
    depends_on formula: "terminal-notifier"
  end

  version "0.34.1"

  on_macos do
    on_arm do
      sha256 "8a1e18c5b45601a1464f29a1b2c906f4d0903974435de5d31d177b37d6f3b167"
      url "https://github.com/gfazioli/octoscope/releases/download/v#{version}/octoscope_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "66f0dda1186a4aa860ddd9aa3140f7b9410e1e50ed4b70e5f7b48c34e01b7ad7"
      url "https://github.com/gfazioli/octoscope/releases/download/v#{version}/octoscope_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6e77b2b55a0791a27b9c9f6e668d8dd87770b1c40346c7a627da9e4173d409af"
      url "https://github.com/gfazioli/octoscope/releases/download/v#{version}/octoscope_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "71491fc66f1c499f61fef709cd19a9fed39862ca105b5dad0d2b809d82bb1245"
      url "https://github.com/gfazioli/octoscope/releases/download/v#{version}/octoscope_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "octoscope"
  desc "Terminal dashboard for your GitHub account"
  homepage "https://github.com/gfazioli/octoscope"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "octoscope"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/octoscope"]
    end
  end

  # No zap stanza required
end
