# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octoscope < Formula
  desc "Terminal dashboard for your GitHub account"
  homepage "https://github.com/gfazioli/octoscope"
  version "0.20.1"
  license "MIT"

  depends_on "terminal-notifier" if OS.mac?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gfazioli/octoscope/releases/download/v0.20.1/octoscope_0.20.1_macOS_x86_64.tar.gz"
      sha256 "adfde5388e25386d50f8107ecdb70513cc6c273237e687bfe55627bba2882439"

      define_method(:install) do
        bin.install "octoscope"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gfazioli/octoscope/releases/download/v0.20.1/octoscope_0.20.1_macOS_arm64.tar.gz"
      sha256 "4dcc0053f28c11dbcd7d1376ef68bd3d352f6e626e5005ea72f0526357efda0f"

      define_method(:install) do
        bin.install "octoscope"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gfazioli/octoscope/releases/download/v0.20.1/octoscope_0.20.1_Linux_x86_64.tar.gz"
      sha256 "76a3961f878b8158922f483ae066549b8b24308c240c1cb98e0d674ff7376c4c"
      define_method(:install) do
        bin.install "octoscope"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gfazioli/octoscope/releases/download/v0.20.1/octoscope_0.20.1_Linux_arm64.tar.gz"
      sha256 "e0dac332e4b6e958973d3f3b00c2ae8d2db323037887838f935ebf194ebbe7c5"
      define_method(:install) do
        bin.install "octoscope"
      end
    end
  end

  test do
    system "#{bin}/octoscope --version"
  end
end
