# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octoscope < Formula
  desc "Terminal dashboard for your GitHub account"
  homepage "https://github.com/gfazioli/octoscope"
  version "0.13.0"
  license "MIT"

  depends_on "terminal-notifier" if OS.mac?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gfazioli/octoscope/releases/download/v0.13.0/octoscope_0.13.0_macOS_x86_64.tar.gz"
      sha256 "a3b27e9975a9b6f732c575e53f05d2080ae815aa77e2cfc6c7cf18b9a63112be"

      define_method(:install) do
        bin.install "octoscope"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gfazioli/octoscope/releases/download/v0.13.0/octoscope_0.13.0_macOS_arm64.tar.gz"
      sha256 "37d6168b00f682266d9c102e77bdd1fef9b32d636270260d54f4cd60c4514b25"

      define_method(:install) do
        bin.install "octoscope"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gfazioli/octoscope/releases/download/v0.13.0/octoscope_0.13.0_Linux_x86_64.tar.gz"
      sha256 "87d2121bcd0527d73a47ece690915207c75a1b6179faa483e72672b13ca08f0a"
      define_method(:install) do
        bin.install "octoscope"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gfazioli/octoscope/releases/download/v0.13.0/octoscope_0.13.0_Linux_arm64.tar.gz"
      sha256 "921449675c32e621612601afa34ca69ad7699ffd6125182c3f605c0b6a366448"
      define_method(:install) do
        bin.install "octoscope"
      end
    end
  end

  test do
    system "#{bin}/octoscope --version"
  end
end
